spring:
  datasource:
    url: jdbc:h2:mem:file:.db/
    driver-class-name: org.h2.Driver
  security:
    user:
      name: sa
      password: sa
  jpa:
    show-sql:
      true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
comments:
  url:
    base: http://localhost:4919/api/comments
    postComments: ${comments.url.base}/{0}/post
    saveComments: ${comments.url.base}/saveAll
logging:
  level:
    org.zalando.logbook: trace
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
logbook:
  exclude:
    -/api/posts/comments
    -/api/upload